### ISSUE TITLE
Deploying via docker and uwsgi

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#466]
## Describe the bug

The documentation on how to deploy with uwsgi seems to be incorrect.

## Steps to reproduce the bug

Following [pywb deployment instructions ](https://pywb.readthedocs.io/en/latest/manual/usage.html?highlight=uwsgi#sample-nginx-configuration)

Using this docker-compose.yaml:

```yaml
version: '2'
services:
  pywb:
    container_name: pywb
    image: webrecorder/pywb:2.2.20190410
    ports:
            - "8080:8080"
            - "8081:8081"
```

Using this nginx vhost:

```nginx
server {
	listen 80;
	
	location / {
        	uwsgi_pass localhost:8081;
        	include uwsgi_params;
        	uwsgi_param UWSGI_SCHEME $scheme;
	}
}
```

nginx is complaining about the connection being closed (from error log):

```
2019/05/21 10:05:10 [error] 26850#26850: *1 upstream prematurely closed connection while reading response header from upstream, client: 95.208.15.188, server: REDACTED, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8081", host: "REDACTED"
```

From pywb docker logs:

```
[pid: 26|app: 0|req: 58/64] 95.208.15.188 () {46 vars in 866 bytes} [Tue May 21 10:03:09 2019] GET /favicon.ico/ => generated 0 bytes in 1 msecs (HTTP/2.0 500) 0 headers in 0 bytes (1 switches on core 99)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pywb-2.2.20190410-py3.7.egg/pywb/apps/frontendapp.py", line 499, in handle_request
  File "/usr/local/lib/python3.7/site-packages/pywb-2.2.20190410-py3.7.egg/pywb/apps/frontendapp.py", line 222, in serve_home
  File "/usr/local/lib/python3.7/site-packages/pywb-2.2.20190410-py3.7.egg/pywb/rewrite/templateview.py", line 229, in render_to_string
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pywb-2.2.20190410-py3.7.egg/pywb/apps/frontendapp.py", line 483, in __call__
  File "/usr/local/lib/python3.7/site-packages/pywb-2.2.20190410-py3.7.egg/pywb/apps/frontendapp.py", line 513, in handle_request
  File "/usr/local/lib/python3.7/site-packages/pywb-2.2.20190410-py3.7.egg/pywb/apps/rewriterapp.py", line 508, in _error_response
  File "/usr/local/lib/python3.7/site-packages/pywb-2.2.20190410-py3.7.egg/pywb/rewrite/templateview.py", line 229, in render_to_string
TypeError: can only concatenate str (not "NoneType") to str
```

Using the pywb container behind via `proxy_pass`on `localhost:8080` works, but doesn't perform well. Curling localhost:8080 also works fine.

## Environment

- OS: Ubuntu 18.04
- nginx: nginx/1.14.0 (Ubuntu)
- docker: version 18.09.6, build 481bc77

**Comment by ikreymer** [comment]
Due to a recent change, the SCRIPT_NAME param now needs to be set, and that's causing the pywb error as nginx does not set it automatically.

This will be fixed in a pywb update, but until then the simple solution is to add `uwsgi_param SCRIPT_NAME "";` to the config. The following should work:

```
server {
	listen 80;
	
	location / {
        	uwsgi_pass localhost:8081;
        	include uwsgi_params;
        	uwsgi_param UWSGI_SCHEME $scheme;
                uwsgi_param SCRIPT_NAME "";
	}
}
```

**Comment by despens** [comment]
That did it, thank you!
