### ISSUE TITLE
pywb fails to load on macOS 11 Big Sur due to fakeredis issue

### ISSUE THREAD

**Issue by robertknight** [webrecorder/pywb#616]
pywb fails to load on macOS 11.0 Big Sur due to an issue with fakeredis, if using Python <= 3.8. The issue in fakeredis is a problem with the `find_library` function from ctypes. See https://bugs.python.org/issue41179. The issue was patched in ctypes for Python 3.9 and 3.10 but will still affect projects using earlier versions of Python.

The code which calls `find_library` doesn't exist in the latest version of fakeredis, so updating the dependency would be one way to solve the problem.

## Steps to reproduce the bug

1. Create an empty virtual environment using an affected version of Python. I used Python 3.6.9
2. Install pywb dependencies following steps in README
3. Try to run the `wayback` binary

It fails to start with the following error:

```shellsession
$ wayback
Traceback (most recent call last):
  File "/Users/robert/.virtualenvs/pywb/bin/wayback", line 33, in <module>
    sys.exit(load_entry_point('pywb==2.5.0', 'console_scripts', 'wayback')())
  File "/Users/robert/.virtualenvs/pywb/lib/python3.6/site-packages/pywb-2.5.0-py3.6.egg/pywb/apps/cli.py", line 20, in wayback
    desc='pywb Wayback Machine Server').run()
  File "/Users/robert/.virtualenvs/pywb/lib/python3.6/site-packages/pywb-2.5.0-py3.6.egg/pywb/apps/cli.py", line 89, in __init__
    self.application = self.load()
  File "/Users/robert/.virtualenvs/pywb/lib/python3.6/site-packages/pywb-2.5.0-py3.6.egg/pywb/apps/cli.py", line 178, in load
    from pywb.apps.frontendapp import FrontEndApp
  File "/Users/robert/.virtualenvs/pywb/lib/python3.6/site-packages/pywb-2.5.0-py3.6.egg/pywb/apps/frontendapp.py", line 26, in <module>
    from pywb.apps.rewriterapp import RewriterApp
  File "/Users/robert/.virtualenvs/pywb/lib/python3.6/site-packages/pywb-2.5.0-py3.6.egg/pywb/apps/rewriterapp.py", line 4, in <module>
    from fakeredis import FakeStrictRedis
  File "/Users/robert/.virtualenvs/pywb/lib/python3.6/site-packages/fakeredis-0.16.0-py3.6.egg/fakeredis.py", line 105, in <module>
    raise ImportError('fakeredis: unable to find libc or equivalent')
ImportError: fakeredis: unable to find libc or equivalent
```

A local workaround is to change the code just above where the error is produced in fakeredis.py from:

```py
_libc_library = find_library('c') or find_library('msvcrt') or find_library('System')
```

To:

```py
_libc_library = 'libc.dylib'
```

## Environment

- macOS 11.2 Big Sur
- Python 3.6.9 installed via pyenv

## Additional context

The issue was originally encountered in the context of a new version of Hypothesis Via proxy service. We currently use Python 3.6.9 for all of our projects, though we plan to update in future as Python 3.6 and 3.7 are in maintenance mode.

**Comment by robrao** [comment]
I had the same issue with python 3.8.5 and BigSur 11.2.2. The workaround provided above also worked for me.

**Comment by robertknight** [comment]
For anyone else coming across this, we implemented a different local workaround in our application that uses pywb: https://github.com/hypothesis/viahtml/pull/56.
