### ISSUE TITLE
fakeredis is in requirements.txt but only required for test according to stup.py

### ISSUE THREAD

**Issue by Hellseher** [webrecorder/pywb#644]
## Describe the bug
`fakeredis` is in requirements.txt but only required for test according to `stup.py`

```
/gnu/store/6pg4zha1rp1d3vlvi6xszxbch4viwanm-python-pywb-2.5.0/bin/pywb
Traceback (most recent call last):
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (fakeredis 1.2.1 (/gnu/store/vhp9xqw1g59fsh2629vpb637bgszmkmb-python-fakeredis-1.2.1/lib/python3.8/site-packages), Requirement.parse('fakeredis<1.0'), {'pywb'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/6pg4zha1rp1d3vlvi6xszxbch4viwanm-python-pywb-2.5.0/bin/.pywb-real", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fakeredis<1.0' distribution was not found and is required by pywb
(guix/linux-gnu)[sharlatan@guxtil ~/Projects/prj/guix-channel]$: /gnu/store/6pg4zha1rp1d3vlvi6xszxbch4viwanm-python-pywb-2.5.0/bin/pywb
Traceback (most recent call last):
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (fakeredis 1.2.1 (/gnu/store/vhp9xqw1g59fsh2629vpb637bgszmkmb-python-fakeredis-1.2.1/lib/python3.8/site-packages), Requirement.parse('fakeredis<1.0'), {'pywb'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gnu/store/6pg4zha1rp1d3vlvi6xszxbch4viwanm-python-pywb-2.5.0/bin/.pywb-real", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/gnu/store/63a1hd1ynsja4029h23q4w1v2czqh2ad-python-3.8.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fakeredis<1.0' distribution was not found and is required by pywb
```

## Steps to reproduce the bug
build and run application from source

```
guix pull
guix install git
git clone https://github.com/Hellseher/guix-channel && cd guix-channel && git checkout be12494879ce7f97a3ec809dabdc8fdfa710b08d
guix build -L . python-pywb
# Then check build path and try to run it
```

## Expected behavior
If `fakeredis` is core dependencies required for run-time application it needs to be listed as such in `setup.py`
Is there any certain reason of  `fakeredis<1.0`?

`fakeredis`
current    -->  May 27, 2021 1.5.1 
required -->  Jan 24, 2019 1.0

## Environment
```
guix describe
Generation 60   Jun 02 2021 17:57:18    (current)
  guix b851f38
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: b851f38a2f2a7bd10b8e25736c4e0e59d0bb3c45
```

**Comment by ikreymer** [comment]
fakeredis is used as part of the app, as a fallback if redis is not available:
https://github.com/webrecorder/pywb/blob/main/pywb/apps/rewriterapp.py#L117

`fakeredis<1.0` is needed as I haven't had a chance to update to latest and 1.x had breaking changes.
