### ISSUE TITLE
Wayback issue

### ISSUE THREAD

**Issue by luroset** [webrecorder/pywb#652]
## Describe the bug
Typing 'wayback' results in:
Z:\>wayback
[Errno 2] No such file or directory: './config.yaml'
2021-06-18 11:43:35,390: [INFO]: Starting Gevent Server on 8080.

Then nothing!

## Steps to reproduce the bug
Type wayback and hit return

## Expected behavior
I'm guessing a web server should be launched?

## Screenshots
![image](https://user-images.githubusercontent.com/86067398/122549673-ac214f00-d02a-11eb-8bcf-1d375dc14d73.png)

## Additional context
I'm a beginner so sorry if I'm missing something obvious!

**Comment by luroset** [comment]
I've since had this:

C:\WINDOWS\system32>wayback
[Errno 2] No such file or directory: './config.yaml'
2021-06-18 15:28:27,295: [INFO]: Starting Gevent Server on 8080
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\wayback.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\pywb\apps\cli.py", line 18, in wayback
    return WaybackCli(args=args,
  File "c:\program files\python38\lib\site-packages\pywb\apps\cli.py", line 117, in run
    self.run_gevent()
  File "c:\program files\python38\lib\site-packages\pywb\apps\cli.py", line 124, in run_gevent
    ge = GeventServer(self.application,
  File "c:\program files\python38\lib\site-packages\pywb\utils\geventserver.py", line 26, in __init__
    self.make_server(app, port, hostname, handler_class, direct=direct)
  File "c:\program files\python38\lib\site-packages\pywb\utils\geventserver.py", line 59, in make_server
    server.init_socket()
  File "c:\program files\python38\lib\site-packages\gevent\pywsgi.py", line 1500, in init_socket
    StreamServer.init_socket(self)
  File "c:\program files\python38\lib\site-packages\gevent\server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "c:\program files\python38\lib\site-packages\gevent\server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "c:\program files\python38\lib\site-packages\gevent\server.py", line 288, in _tcp_listener
    sock.bind(address)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('0.0.0.0', 8080)

**Comment by ikreymer** [comment]
In the first message, the web server is launched. You should be able to open your browser and load `http://localhost:8080/`

In the second message, it's telling you that the web server is already running on port 8080, hence the error.

The missing `config.yaml` file is not really an error (should change it to a warning so its less confusing).

To have something in your archive, you'll need to add some WARCs files to a collection, for example by running:
`wb-manager init my-web-archive` and then adding `wb-manager add my-web-archive /path/to/some/warc/files/my.warc.gz`
The WARCs will be added in the directory that you run it, in this case, directly in the Z:\ drive it looks like. You may want to create a separate directory for your web archives, and then run wayback from there.

For more info, check out the guide at: https://pywb.readthedocs.io/en/latest/manual/usage.html#getting-started
