### ISSUE TITLE
Error: thumbnail-generator

### ISSUE THREAD

**Issue by peterchanws** [webrecorder/pywb#734]
I have no problem seeing the archived sire in my desktop Archive Web.Page

wacz file: https://argo-qa.stanford.edu/view/druid:vg019xs5734

https://argo-qa.stanford.edu/view/druid:bx407sr4089
Error message:
Error: thumbnail-generator : Thumbnail for druid druid:bx407sr4089 and https://www.instagram.com/stanford_woco/stanford_woco/ can't be generated. (node:3107374) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn tmp/bx407sr4089.jpeg ENOENT TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md at onClose (/opt/app/was/was_robot_suite/releases/20220705165013/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:286:20) at ChildProcess.<anonymous> (/opt/app/was/was_robot_suite/releases/20220705165013/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:280:24) at ChildProcess.emit (events.js:400:28) at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12) at onErrorNT (internal/child_process.js:472:16) at processTicksAndRejections (internal/process/task_queues.js:82:21) (Use `node --trace-warnings ...` to show where the warning was created) (node:3107374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:3107374) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by peterchanws** [comment]
Sorry, I intended to post this in [Stanford's ](https://github.com/sul-dlss/was-pywb)
