### ISSUE TITLE
Replay of images failes in pywb (works with archiveweb.page): warcio.exceptions.ArchiveLoadFailed: Original for revisit record could not be loaded

### ISSUE THREAD

**Issue by steph-nb** [webrecorder/pywb#802]
## Expected behavior
Pictures contained in the attached warc.gz should be served and displayed.
[republik1_0.warc.gz](https://github.com/webrecorder/pywb/files/10497691/republik1_0.warc.gz)
[republik1_1.warc.gz](https://github.com/webrecorder/pywb/files/10497693/republik1_1.warc.gz)

Both warc.gz are exactly the same crawl (done with archiveweb.page. Just WARC1/0 vs. WARC1/1; in fact none of them works).

## What actually happened
1. Index one of the attached warc.gz with wb-manager
2. Open this page in your pywb: https://www.republik.ch/2022/02/08/mitdebattieren-leicht-gemacht
3. Scroll a little down until the images (gifs) should appear.
4. They are missing (although being contained in the crawl)

## Log
127.0.0.1 - - [2023-01-25 09:57:35] "POST /test/resource/postreq?url=https%3A%2F%2Fcdn.repub.ch%2Fs3%2Frepublik-assets%2Frepos%2Frepublik%2Farticle-so-geht-das-hier%2Fimages%2F0a0eb9c4a1e48ed74b871aca9cd46d788a8b995d.gif%3Fsize%3D922x576%26format%3Dauto%26resize%3D922x&closest=20230125084600&matchType=exact HTTP/1.1" 503 442 0.034582
2023-01-25 09:57:35,446: [DEBUG]: http://localhost:54389 "POST /test/resource/postreq?url=https%3A%2F%2Fcdn.repub.ch%2Fs3%2Frepublik-assets%2Frepos%2Frepublik%2Farticle-so-geht-das-hier%2Fimages%2F0a0eb9c4a1e48ed74b871aca9cd46d788a8b995d.gif%3Fsize%3D922x576%26format%3Dauto%26resize%3D922x&closest=20230125084600&matchType=exact HTTP/1.1" 503 143
127.0.0.1 - - [2023-01-25 09:57:35] "GET /test/20230125084600im_/https://cdn.repub.ch/s3/republik-assets/repos/republik/article-so-geht-das-hier/images/0a0eb9c4a1e48ed74b871aca9cd46d788a8b995d.gif?size=922x576&format=auto&resize=922x HTTP/1.1" 503 1842 0.086629
2023-01-25 09:57:37,862: [DEBUG]: Starting new HTTP connection (1): localhost:54389
Dir .\collections\test\indexes\ unchanged
Dir .\collections\test\indexes\ unchanged
Traceback (most recent call last):
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.3-py3.6.egg\pywb\warcserver\handlers.py", line 160, in __call__
    out_headers, resp = loader(cdx, params)
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.3-py3.6.egg\pywb\warcserver\resource\responseloader.py", line 37, in __call__
    entry = self.load_resource(cdx, params)
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.3-py3.6.egg\pywb\warcserver\resource\responseloader.py", line 206, in load_resource
    local_index_query))
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.3-py3.6.egg\pywb\warcserver\resource\resolvingloader.py", line 89, in load_headers_and_payload
    cdx_loader)
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.3-py3.6.egg\pywb\warcserver\resource\resolvingloader.py", line 217, in _load_different_url_payload
    raise ArchiveLoadFailed(self.MISSING_REVISIT_MSG)
warcio.exceptions.ArchiveLoadFailed: Original for revisit record could not be loaded
NoneType: None
127.0.0.1 - - [2023-01-25 09:57:37] "POST /test/resource/postreq?url=https%3A%2F%2Fcdn.repub.ch%2Fs3%2Frepublik-assets%2Frepos%2Frepublik%2Farticle-so-geht-das-hier%2Fimages%2Fdca51f43ef2d23696d12898735a8b68b65eae0ac.gif%3Fsize%3D992x544%26format%3Dauto%26resize%3D992x&closest=20230125084600&matchType=exact HTTP/1.1" 503 442 0.048205
2023-01-25 09:57:37,915: [DEBUG]: http://localhost:54389 "POST /test/resource/postreq?url=https%3A%2F%2Fcdn.repub.ch%2Fs3%2Frepublik-assets%2Frepos%2Frepublik%2Farticle-so-geht-das-hier%2Fimages%2Fdca51f43ef2d23696d12898735a8b68b65eae0ac.gif%3Fsize%3D992x544%26format%3Dauto%26resize%3D992x&closest=20230125084600&matchType=exact HTTP/1.1" 503 143
127.0.0.1 - - [2023-01-25 09:57:37] "GET /test/20230125084600im_/https://cdn.repub.ch/s3/republik-assets/repos/republik/article-so-geht-das-hier/images/dca51f43ef2d23696d12898735a8b68b65eae0ac.gif?size=992x544&format=auto&resize=992x HTTP/1.1" 503 1842 0.059209

Why can't pywb serve the response body with the same payload digest?

**Comment by steph-nb** [comment]
@tw4l : Were able to check it on your side in the meantime?
Can you confirm, it is a pywb issue?
(And can you fix it please? Thx a lot)

**Comment by tw4l** [comment]
Hi @steph-nb , sorry I've been kept busy on other tasks so haven't had a chance to investigate yet but I will check it out soon! At first glance seems like a replay issue - replayweb.page and pywb use different replay systems so it's a fair bit of work to keep them at parity. We have a PR that handles JS modules better in pywb that might help. I'll update here when I've had a chance to look.

**Comment by steph-nb** [comment]
Hi @tw4l , yes of course, I understand. I faced the same issue again, and therefore just wanted to make sure that it is not forgotten ;-)
Many thanks and BR

**Comment by steph-nb** [comment]
Hi folks,
still this issue is unresolved.
Therefore I upload another and maximally reduced example:
[20180117_30-jahre-vor-gericht.warc.gz](https://github.com/webrecorder/pywb/files/14773833/20180117_30-jahre-vor-gericht.warc.gz)

It only consists of 3 captued URLs.
One response with status 200 of this URL:
https://cdn.repub.ch/s3/republik-assets/repos/republik/article-30-jahre-vor-gericht/images/e508169162623ea58b1069ff1e8c7128c15293b2.gif?size=850x567&format=auto&resize=333x
And two revisits with these URLs:
https://cdn.repub.ch/s3/republik-assets/repos/republik/article-30-jahre-vor-gericht/images/e508169162623ea58b1069ff1e8c7128c15293b2.gif?size=850x567&format=auto&resize=665x
https://cdn.repub.ch/s3/republik-assets/repos/republik/article-30-jahre-vor-gericht/images/e508169162623ea58b1069ff1e8c7128c15293b2.gif?size=850x567&format=auto&resize=850x

All having the same digest of:
sha256:bb5fe7c707048130403185e469d1e080fe2a50a270902e3c02da374b3b809454

still pywb is not able to serve the object the revisits point to:

Traceback (most recent call last):
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.4-py3.6.egg\pywb\warcserver\handlers.py", line 160, in __call__
    out_headers, resp = loader(cdx, params)
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.4-py3.6.egg\pywb\warcserver\resource\responseloader.py", line 37, in __call__
    entry = self.load_resource(cdx, params)
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.4-py3.6.egg\pywb\warcserver\resource\responseloader.py", line 206, in load_resource
    local_index_query))
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.4-py3.6.egg\pywb\warcserver\resource\resolvingloader.py", line 89, in load_headers_and_payload
    cdx_loader)
  File "C:\Tools\pywb\lib\site-packages\pywb-2.7.4-py3.6.egg\pywb\warcserver\resource\resolvingloader.py", line 217, in _load_different_url_payload
    raise ArchiveLoadFailed(self.MISSING_REVISIT_MSG)
warcio.exceptions.ArchiveLoadFailed: Original for revisit record could not be loaded
NoneType: None
127.0.0.1 - - [2024-03-27 14:15:56] "POST /republik_bastel/resource/postreq?url=https%3A%2F%2Fcdn.repub.ch%2Fs3%2Frepublik-assets%2Frepos%2Frepublik%2Farticle-30-jahre-vor-gericht%2Fimages%2Fe508169162623ea58b1069ff1e8c7128c15293b2.gif%3Fsize%3D850x567%26format%3Dauto%26resize%3D850x&closest=20240327122236&matchType=exact HTTP/1.1" 503 442 0.008018
